#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

#ENGINE_PATH = File.expand_path('../..',  __FILE__)
#load File.expand_path('../../spec/dummy/script/rails',  __FILE__)

#require 'rails/all'
#require 'rails/commands'

#!/usr/bin/env ruby
ENGINE_ROOT = File.expand_path('../..', __FILE__)
ENGINE_PATH = File.expand_path('../../lib/spree_flexi_variants/engine', __FILE__)
require 'rails/all'
require 'rails/engine/commands'